export const coursesData = [
  {
    id: "dsa",
    title: "Data Structures & Algorithms",
    description: "Master the fundamentals of computer science with comprehensive DSA training",
    icon: "Binary",
    color: "linear-gradient(to right, #3b82f6, #06b6d4)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Get introduced to the world of Data Structures and Algorithms. Understand why they are crucial for software development and problem-solving.",
            videoUrl: "https://www.youtube.com/embed/8hly31xKli0",
            notes: "Data Structures and Algorithms form the foundation of computer science. They help us organize data efficiently and solve complex problems systematically.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Explore the career opportunities available after mastering DSA, from FAANG companies to competitive programming.",
            videoUrl: "https://www.youtube.com/embed/BBpAmxU_NQo",
            notes: "DSA skills are essential for technical interviews at top tech companies. Companies like Google, Amazon, Facebook, and Microsoft heavily test DSA knowledge.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn fundamental concepts including time complexity, space complexity, Big O notation, and algorithmic thinking.",
            videoUrl: "https://www.youtube.com/embed/D6xkbGLQesk",
            notes: "Time Complexity: Measures how the runtime of an algorithm changes with input size. Big O Notation: Describes the upper bound of complexity.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up your development environment with the right tools for practicing DSA effectively.",
            videoUrl: "https://www.youtube.com/embed/vz1RlUyrc3w",
            notes: "Recommended tools: VS Code, LeetCode account, CodeChef/Codeforces for practice, GitHub for version control.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build practical projects to solidify your DSA knowledge with real implementations.",
            videoUrl: "https://www.youtube.com/embed/RBSGKlAvoiM",
            notes: "Project ideas: Implement a custom HashMap, Build a file compression tool using Huffman coding, Create a pathfinding visualizer.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Understand how DSA concepts are applied in production systems and real-world applications.",
            videoUrl: "https://www.youtube.com/embed/6aEyTjOwlJU",
            notes: "Real-world applications: Google Maps uses graph algorithms, Netflix uses recommendation algorithms, Databases use B-trees for indexing.",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Optimization Techniques",
            description: "Master advanced optimization techniques including dynamic programming, greedy algorithms, and divide-and-conquer.",
            videoUrl: "https://www.youtube.com/embed/oBt53YbR9Kk",
            notes: "Advanced techniques: Dynamic Programming, Greedy Algorithms, Divide and Conquer, Backtracking, Advanced graph algorithms.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn industry best practices for writing production-grade algorithms and passing technical interviews.",
            videoUrl: "https://www.youtube.com/embed/3Q_oYDQ2whs",
            notes: "Best practices: Write clean readable code, test edge cases thoroughly, consider trade-offs between time and space complexity.",
            completed: false,
          },
        ],
      },
    ],
  },

  {
    id: "mern",
    title: "Web Development (MERN Stack)",
    description: "Build full-stack web applications using MongoDB, Express, React, and Node.js",
    icon: "Code2",
    color: "linear-gradient(to right, #22c55e, #10b981)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Introduction to the MERN stack and modern web development practices.",
            videoUrl: "https://www.youtube.com/embed/7CqJlxBYj-M",
            notes: "The MERN stack combines MongoDB, Express, React, and Node.js for full-stack JavaScript development.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Explore the vast opportunities in web development and the demand for MERN stack developers.",
            videoUrl: "https://www.youtube.com/embed/SBB1YtwODT0",
            notes: "MERN stack developers are in high demand. Career paths include Frontend, Backend, and Full-Stack Developer roles.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn the fundamentals of each technology in the MERN stack.",
            videoUrl: "https://www.youtube.com/embed/Oe421EPjeBE",
            notes: "Core concepts: React components and hooks, Node.js event loop, Express middleware, MongoDB schema design, RESTful API design.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up your development environment with all necessary tools and dependencies.",
            videoUrl: "https://www.youtube.com/embed/RLtyhwFtXQA",
            notes: "Required tools: Node.js, MongoDB, VS Code, Postman for API testing, Git, React Developer Tools.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build real-world projects to apply your MERN stack knowledge.",
            videoUrl: "https://www.youtube.com/embed/98BzS5Oz5E4",
            notes: "Project ideas: E-commerce platform, Social media app, Task management application, Real-time chat with Socket.io.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Understand how MERN stack is used in production applications.",
            videoUrl: "https://www.youtube.com/embed/F2JCjVSZlG0",
            notes: "Real-world: Netflix uses Node.js for backend, Facebook built React for its UI, Uber uses Node.js for its matching system.",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Optimization Techniques",
            description: "Master performance optimization, caching, and scalability patterns.",
            videoUrl: "https://www.youtube.com/embed/GqmQg-cszw4",
            notes: "Optimization: Code splitting, lazy loading, database indexing, Redis caching, SSR with Next.js, API rate limiting.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn professional development practices used in production environments.",
            videoUrl: "https://www.youtube.com/embed/I6ypD7qv3Z8",
            notes: "Best practices: Unit and integration tests, TypeScript, CI/CD pipelines, OWASP security, Docker, deploy on AWS/Vercel.",
            completed: false,
          },
        ],
      },
    ],
  },

  {
    id: "ar-vr",
    title: "AR/VR Development",
    description: "Create immersive experiences with Augmented and Virtual Reality technologies",
    icon: "Glasses",
    color: "linear-gradient(to right, #a855f7, #ec4899)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Introduction to AR/VR technologies and their applications in modern industries.",
            videoUrl: "https://www.youtube.com/embed/5sX0HJPRV2s",
            notes: "AR overlays digital content onto the real world, VR creates fully immersive digital environments. These technologies are revolutionizing gaming, healthcare, education, and retail.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Discover exciting career opportunities in the rapidly growing AR/VR industry.",
            videoUrl: "https://www.youtube.com/embed/tpbLiTSVrCI",
            notes: "AR/VR careers: AR/VR Developer, 3D Artist, UX Designer for spatial computing. Companies like Meta, Apple, Microsoft are investing heavily.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn fundamental concepts of 3D graphics, spatial computing, and immersive design.",
            videoUrl: "https://www.youtube.com/embed/gBmNnE0sFGg",
            notes: "Core concepts: 3D coordinate systems, rendering pipelines, spatial tracking, hand tracking, stereoscopic rendering, physics engines.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up your AR/VR development environment with Unity, Unreal Engine, or web-based frameworks.",
            videoUrl: "https://www.youtube.com/embed/yPpxJglbFj4",
            notes: "Essential tools: Unity with XR Toolkit, Meta Quest SDK, ARCore/ARKit, WebXR, Blender for 3D modeling.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build engaging AR/VR applications from games to practical tools.",
            videoUrl: "https://www.youtube.com/embed/gGYtahQjmWQ",
            notes: "Project ideas: VR escape room, AR furniture placement app, virtual museum tour, VR training simulator, AR navigation app.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Explore how AR/VR is being used across various industries.",
            videoUrl: "https://www.youtube.com/embed/WzfDo2Wpxks",
            notes: "Industry applications: Healthcare (surgical training), Retail (virtual try-ons), Real estate (virtual tours), Education (immersive learning).",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Optimization Techniques",
            description: "Master performance optimization for smooth, comfortable AR/VR experiences.",
            videoUrl: "https://www.youtube.com/embed/g0JiNxhKKYs",
            notes: "Optimization: LOD systems, occlusion culling, texture compression, foveated rendering, maintaining 90-120 FPS to prevent motion sickness.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn professional standards for AR/VR development and user experience.",
            videoUrl: "https://www.youtube.com/embed/Qwh1LBzz3AU",
            notes: "Best practices: Design for comfort, test with real users, follow platform guidelines, implement safety boundaries, optimize for battery life.",
            completed: false,
          },
        ],
      },
    ],
  },

  {
    id: "ai-ml",
    title: "AI & Machine Learning",
    description: "Master artificial intelligence and machine learning algorithms and applications",
    icon: "Brain",
    color: "linear-gradient(to right, #f97316, #ef4444)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Introduction to AI and ML concepts, history, and their transformative impact.",
            videoUrl: "https://www.youtube.com/embed/ad79nYk2keg",
            notes: "AI enables machines to simulate human intelligence. ML is a subset that allows systems to learn from data. This field covers supervised, unsupervised, and reinforcement learning.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Explore the lucrative and rapidly expanding AI/ML career landscape.",
            videoUrl: "https://www.youtube.com/embed/2dU5FK7tBuU",
            notes: "AI/ML careers: ML Engineer, Data Scientist, AI Research Scientist, NLP Engineer. Salaries range from $120K to $400K+.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn foundational ML concepts including algorithms, models, and evaluation metrics.",
            videoUrl: "https://www.youtube.com/embed/ukzFI9rgwfU",
            notes: "Core concepts: Supervised vs Unsupervised learning, Decision Trees, Neural Networks, overfitting/underfitting, evaluation metrics.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up your ML development environment with Python, TensorFlow, and essential libraries.",
            videoUrl: "https://www.youtube.com/embed/6kCxxvFfhJk",
            notes: "Essential tools: Python with Anaconda, Jupyter Notebooks, NumPy, Pandas, Scikit-learn, TensorFlow/PyTorch, Google Colab.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build practical ML projects to demonstrate your skills.",
            videoUrl: "https://www.youtube.com/embed/fiz1ORTBGpY",
            notes: "Project ideas: Image classification, sentiment analysis, house price prediction, recommendation system, fraud detection.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Understand how AI/ML powers modern applications and services.",
            videoUrl: "https://www.youtube.com/embed/mJeNghZXtMo",
            notes: "Real-world: Netflix recommendations, Tesla self-driving, Google Translate, Face ID, spam filtering, medical diagnosis.",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Optimization Techniques",
            description: "Master advanced techniques including deep learning, transformers, and model optimization.",
            videoUrl: "https://www.youtube.com/embed/kWLed8o5M2Y",
            notes: "Advanced: CNNs, RNNs, Transformers, transfer learning, hyperparameter tuning, model compression, GANs, diffusion models.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn MLOps, deployment strategies, and production ML best practices.",
            videoUrl: "https://www.youtube.com/embed/Clfv70ztMhI",
            notes: "Best practices: MLflow for experiment tracking, Flask/FastAPI for deployment, Docker, CI/CD for ML, cloud platforms (AWS SageMaker, GCP).",
            completed: false,
          },
        ],
      },
    ],
  },

  {
    id: "cybersecurity",
    title: "Cybersecurity",
    description: "Learn to protect systems, networks, and data from digital attacks",
    icon: "Shield",
    color: "linear-gradient(to right, #ef4444, #f43f5e)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Introduction to cybersecurity principles, threat landscape, and defense strategies.",
            videoUrl: "https://www.youtube.com/embed/inWWhr5tnEA",
            notes: "Cybersecurity protects systems, networks, and data from theft and unauthorized access. Key areas include network security, application security, and disaster recovery.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Discover rewarding careers in the high-demand cybersecurity field.",
            videoUrl: "https://www.youtube.com/embed/MkUBKAb95s8",
            notes: "Cybersecurity careers: Security Analyst, Penetration Tester, Security Engineer, Ethical Hacker, CISO. Salaries range from $85K to $250K+.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn fundamental security concepts, the CIA triad, and common vulnerabilities.",
            videoUrl: "https://www.youtube.com/embed/U_P23SqJaDc",
            notes: "Core concepts: CIA Triad, Authentication vs Authorization, Encryption, Hashing, OWASP Top 10, Firewalls, Risk assessment.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up your security testing lab with essential tools and platforms.",
            videoUrl: "https://www.youtube.com/embed/WnN6dbos5u8",
            notes: "Essential tools: Kali Linux, Wireshark, Burp Suite, Metasploit, Nmap, TryHackMe and HackTheBox for practice.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build practical security projects and practice ethical hacking.",
            videoUrl: "https://www.youtube.com/embed/2_lswM1S264",
            notes: "Project ideas: Secure authentication system, vulnerability scanner, network monitoring tool, honeypot, intrusion detection system.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Understand how cybersecurity principles are applied to protect organizations.",
            videoUrl: "https://www.youtube.com/embed/z5nc9MDbvkw",
            notes: "Real-world: Banks use MFA and encryption, healthcare protects data with HIPAA, companies use SOC teams, bug bounty programs.",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Advanced Techniques",
            description: "Master advanced security techniques including malware analysis and exploit development.",
            videoUrl: "https://www.youtube.com/embed/LZJNxZkdmxc",
            notes: "Advanced: Reverse engineering, binary exploitation, web app pentesting (SQLi, XSS), Active Directory attacks, threat hunting.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn industry standards, compliance requirements, and security operations.",
            videoUrl: "https://www.youtube.com/embed/5-SysQy79w4",
            notes: "Best practices: NIST Cybersecurity Framework, defense in depth, incident response planning, patch management, GDPR/SOC 2 compliance.",
            completed: false,
          },
        ],
      },
    ],
  },

  {
    id: "cloud",
    title: "Cloud Computing",
    description: "Master cloud platforms and modern infrastructure management",
    icon: "Cloud",
    color: "linear-gradient(to right, #0ea5e9, #3b82f6)",
    sections: [
      {
        id: "intro",
        title: "Introduction",
        subsections: [
          {
            id: "overview",
            title: "Overview",
            description: "Introduction to cloud computing models, services, and major providers.",
            videoUrl: "https://www.youtube.com/embed/M988_fsOSWo",
            notes: "Cloud computing delivers services over the internet. Three main models: IaaS, PaaS, SaaS. Major providers: AWS, Azure, Google Cloud.",
            completed: false,
          },
          {
            id: "career",
            title: "Career Scope",
            description: "Explore lucrative cloud computing career opportunities and certifications.",
            videoUrl: "https://www.youtube.com/embed/kFNYQVnfaxU",
            notes: "Cloud careers: Cloud Engineer, DevOps Engineer, Cloud Architect, SRE. Certifications like AWS Solutions Architect are highly valued. Salaries $95K-$220K+.",
            completed: false,
          },
        ],
      },
      {
        id: "fundamentals",
        title: "Fundamentals",
        subsections: [
          {
            id: "core-concepts",
            title: "Core Concepts",
            description: "Learn fundamental cloud concepts, architecture patterns, and service models.",
            videoUrl: "https://www.youtube.com/embed/dH0yz-Osy54",
            notes: "Core concepts: Virtualization, containerization, scalability, high availability, load balancing, IAM, pay-as-you-go pricing.",
            completed: false,
          },
          {
            id: "tools",
            title: "Tools Setup",
            description: "Set up cloud accounts and learn essential tools for cloud development.",
            videoUrl: "https://www.youtube.com/embed/3hLmDS179YE",
            notes: "Essential tools: AWS/Azure/GCP free tier, Terraform for IaC, Docker, Kubernetes, Ansible, monitoring tools.",
            completed: false,
          },
        ],
      },
      {
        id: "intermediate",
        title: "Intermediate",
        subsections: [
          {
            id: "projects",
            title: "Projects",
            description: "Build cloud-based applications and infrastructure projects.",
            videoUrl: "https://www.youtube.com/embed/3MBQvterQhY",
            notes: "Project ideas: Three-tier web app, auto-scaling infrastructure, serverless REST API, data pipeline, containerized microservices on Kubernetes.",
            completed: false,
          },
          {
            id: "real-world",
            title: "Real-world Use Cases",
            description: "Understand how companies leverage cloud computing for business solutions.",
            videoUrl: "https://www.youtube.com/embed/8HtLfvhV0hU",
            notes: "Real-world: Netflix on AWS, Spotify on Google Cloud, Capital One migrated to AWS, Airbnb uses AWS for global infrastructure.",
            completed: false,
          },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        subsections: [
          {
            id: "optimization",
            title: "Optimization Techniques",
            description: "Master cost optimization, performance tuning, and advanced cloud architectures.",
            videoUrl: "https://www.youtube.com/embed/XQSxHqZdLZQ",
            notes: "Optimization: Right-sizing, reserved/spot instances, CDN caching, serverless computing, blue-green deployments, IaC best practices.",
            completed: false,
          },
          {
            id: "industry",
            title: "Industry Practices",
            description: "Learn DevOps, security best practices, and cloud-native development.",
            videoUrl: "https://www.youtube.com/embed/Xrgk023l4lI",
            notes: "Best practices: CI/CD pipelines, Terraform/CloudFormation, Well-Architected Framework, encryption, least privilege, DevOps culture.",
            completed: false,
          },
        ],
      },
    ],
  },
];